language: node_js
node_js: "6.7.0"
before_script:
  - npm install -g gulp
  - npm install -g bower 
  - npm install
  - bower install

script:
    - gulp build
#    - gulp docs - error docs build now
#    - tree -D
    - tar -zcf ../clickhouse-frontend.tar.gz -C .. clickhouse-frontend

# for travis state view, debug deploy
#addons:
#  apt:
#    packages:
#        - tree

deploy:
  skip_cleanup: true
  tags: true
  provider: releases
  on:
    tags: true
  api_key: $GITHUB_TOKEN
  file:
    - "../clickhouse-frontend.tar.gz"